### PR TITLE
Finish GCI-7

### PR DESCRIPTION
**Pull request by hexafraction**

### CODE REVIEW

**Comment by harsha89** [comment]
Looks good!

**Comment by dkayiwa** [comment]
@hexafraction are you still available to do some extra changes for this?

**Comment by hexafraction** [comment]
@dkayiwa I have less time than usual but I can spare some time; what needs to be done?

**Comment by dkayiwa** [comment]
@hexafraction start by pulling the latest changes from upstream. Then tell me if you get any conflicts and if you can compile successfully.

**Pull request closed without merging**
